create database bank;

use bank;

CREATE TABLE BRANCH(
BRANCH_ID VARCHAR(30),
BRANCH_NAME VARCHAR(30),
BRANCH_ADDRESS VARCHAR(50),
ASSESTS DECIMAL(15,3)
);

ALTER TABLE BRANCH ADD PRIMARY KEY(BRANCH_ID);

CREATE TABLE BANKER(
BANKER_ID INT PRIMARY KEY,
BANKER_NAME VARCHAR(30) NOT NULL ,
BRANCH_ID VARCHAR(30),
FOREIGN KEY(BRANCH_ID) REFERENCES BRANCH(BRANCH_ID)
);

CREATE TABLE ACCOUNT(
ACCOUNT_ID VARCHAR(20),
ACCOUNT_BALANCE DECIMAL(15,4),
ACCOUNT_TYPE varchar(20),
BRANCH_ID VARCHAR(30),
FOREIGN KEY(BRANCH_ID) REFERENCES BRANCH(BRANCH_ID)
);

ALTER TABLE ACCOUNT ADD PRIMARY KEY(ACCOUNT_ID);

CREATE TABLE LOAN(
LOAN_ID VARCHAR(20) PRIMARY KEY,
ISSUED_AMOUNT DECIMAL(15,2),
REMAINING_AMOUNT DECIMAL(15,2),
BRANCH_ID VARCHAR(30),
ACCOUNT_ID VARCHAR(20),
FOREIGN KEY(BRANCH_ID) REFERENCES BRANCH(BRANCH_ID),
FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);


CREATE TABLE LOAN_PAYMENT(
LOAN_PAYMENT_ID VARCHAR(20) PRIMARY KEY,
AMOUNT DECIMAL(15,2),
LOAN_ID VARCHAR(20),
FOREIGN KEY(LOAN_ID) REFERENCES LOAN(LOAN_ID)
);


CREATE TABLE CUSTOMER(
CUSTOMER_ID VARCHAR(20),
CUSTOMER_NAME VARCHAR(30),
DATE_OF_BIRTH DATE,
MOBILE_NO BIGINT,
ACCOUNT_ID VARCHAR(20),
FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);

ALTER TABLE CUSTOMER ADD PRIMARY KEY(CUSTOMER_ID); 

CREATE TABLE BORROWER(
BORROWER_ID VARCHAR(20) PRIMARY KEY,
LOAN_ID VARCHAR(20),
CUSTOMER_ID VARCHAR(20),
FOREIGN KEY(LOAN_ID) REFERENCES LOAN(LOAN_ID), 
FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE TRANSACTION(
TRANSACTION_ID VARCHAR(20) PRIMARY KEY,
ACCOUNT_ID VARCHAR(20),
CUSTOMER_ID VARCHAR(20),
AMOUNT DECIMAL(15,2),
FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID),
FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);


CREATE TABLE CREDIT_CARD(
CREDIT_CARD_ID VARCHAR(20) PRIMARY KEY,
EXPIRY_DATE DATE,
CARD_LIMIT DECIMAL(10,2),
ACCOUNT_ID VARCHAR(20),
CUSTOMER_ID VARCHAR(20),
FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID),
FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);
